name: neom_maps_services
description: Google Maps Web Services Library Maintained by Open Neom
version: 2.0.0
homepage: https://github.com/Cyberneom/neom_maps_services

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  http: ^1.6.0
  json_annotation: ^4.9.0
  logger: ^2.6.2

dev_dependencies:
  test: ^1.26.3
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  coverage: ^1.15.0
